spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&zeroDateTimeBehavior=convertToNull&&characterEncoding=utf8
     username: root
     password: pppp
     driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  redis:
#  redis数据库索引（默认0）默认端口号：6379 默认密码为空
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    pool:
#    连接池最大连接数（使用负值表示没有限制）
      max-active: 10
#    连接池中的最大空闲链接
      max-idle: 6
#    连接池中的最小空闲链接
      min-idle: 3
#    连接池中的最大等待时间1s
      max-wait: 1000
#    连接超时时间1s（毫秒；0表示没有超时时间）
      timeout: 1000

